services:
  - type: web
    name: blitzproof-backend
    env: node
    plan: free
    buildCommand: npm ci --only=production && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: ETHERSCAN_API_KEY
        sync: false
      - key: POLYGONSCAN_API_KEY
        sync: false
      - key: BSCSCAN_API_KEY
        sync: false
      - key: ARBISCAN_API_KEY
        sync: false
      - key: OPTIMISM_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false 